name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/wifi.png
    - assets/page-1/images/iconly-bold-star.png
    - assets/page-1/images/iconsax-linear-user.png
    - assets/page-1/images/wifi-UGH.png
    - assets/page-1/images/iconly-bold-star-t73.png
    - assets/page-1/images/iconsax-linear-walletcheck.png
    - assets/page-1/images/cart.png
    - assets/page-1/images/cellular.png
    - assets/page-1/images/cart-rgq.png
    - assets/page-1/images/home.png
    - assets/page-1/images/iconly-bold-star-iuP.png
    - assets/page-1/images/search.png
    - assets/page-1/images/ellipse-12.png
    - assets/page-1/images/brands.png
    - assets/page-1/images/iconsax-linear-lockslash.png
    - assets/page-1/images/home-J6V.png
    - assets/page-1/images/battery.png
    - assets/page-1/images/battery-fbP.png
    - assets/page-1/images/search-Adf.png
    - assets/page-1/images/iconsax-outline-arrowleft.png
    - assets/page-1/images/mask-group.png
    - assets/page-1/images/battery-rgR.png
    - assets/page-1/images/iconsax-linear-user-DWy.png
    - assets/page-1/images/heart.png
    - assets/page-1/images/wifi-LT3.png
    - assets/page-1/images/iconsax-linear-lockslash-mpV.png
    - assets/page-1/images/battery-tjb.png
    - assets/page-1/images/iconly-bold-star-whb.png
    - assets/page-1/images/sneaker-image-1.png
    - assets/page-1/images/iconsax-linear-card.png
    - assets/page-1/images/iconsax-linear-scanbarcode.png
    - assets/page-1/images/menu.png
    - assets/page-1/images/search-geM.png
    - assets/page-1/images/iconly-bold-star-2TK.png
    - assets/page-1/images/home-2XB.png
    - assets/page-1/images/iconly-bold-star-MpM.png
    - assets/page-1/images/iconly-bold-star-Aoj.png
    - assets/page-1/images/iconsax-bold-facebook.png
    - assets/page-1/images/heart-P9K.png
    - assets/page-1/images/wifi-gu7.png
    - assets/page-1/images/cart-qn1.png
    - assets/page-1/images/cellular-nhF.png
    - assets/page-1/images/heart-R5K.png
    - assets/page-1/images/puma.png
    - assets/page-1/images/iconsax-linear-eyeslash.png
    - assets/page-1/images/iconly-bold-star-hey.png
    - assets/page-1/images/user.png
    - assets/page-1/images/iconly-bold-star-iXT.png
    - assets/page-1/images/user-4bK.png
    - assets/page-1/images/iconly-bold-arrow-left-square.png
    - assets/page-1/images/user-dSh.png
    - assets/page-1/images/iconsax-linear-more.png
    - assets/page-1/images/cellular-1vy.png
    - assets/page-1/images/battery-THB.png
    - assets/page-1/images/home-RsX.png
    - assets/page-1/images/search-qGM.png
    - assets/page-1/images/iconsax-linear-lockslash-PUD.png
    - assets/page-1/images/battery-7f7.png
    - assets/page-1/images/iconly-bold-star-7DB.png
    - assets/page-1/images/heart-ooP.png
    - assets/page-1/images/iconsax-outline-arrowleft-juK.png
    - assets/page-1/images/cellular-yz1.png
    - assets/page-1/images/iconsax-linear-money.png
    - assets/page-1/images/iconly-bold-star-c3s.png
    - assets/page-1/images/heart-MN9.png
    - assets/page-1/images/iconsax-linear-walletmoney.png
    - assets/page-1/images/iconsax-linear-eyeslash-Rg5.png
    - assets/page-1/images/heart-5H3.png
    - assets/page-1/images/cellular-t9w.png
    - assets/page-1/images/cellular-Cpq.png
    - assets/page-1/images/wifi-BaH.png
    - assets/page-1/images/cart-iaD.png
    - assets/page-1/images/home-eED.png
    - assets/page-1/images/wifi-JdX.png
    - assets/page-1/images/battery-wku.png
    - assets/page-1/images/mask-group-7JZ.png
    - assets/page-1/images/iconsax-bold-apple.png
    - assets/page-1/images/user-eWM.png
    - assets/page-1/images/wifi-jw7.png
    - assets/page-1/images/nike.png
    - assets/page-1/images/iconly-bold-star-Rhs.png
    - assets/page-1/images/iconly-bold-star-KHT.png
    - assets/page-1/images/brands-X7w.png
    - assets/page-1/images/iconly-bold-star-bRs.png
    - assets/page-1/images/search-29o.png
    - assets/page-1/images/iconly-bold-star-SGh.png
    - assets/page-1/images/iconly-bold-star-vAM.png
    - assets/page-1/images/mask-group-Gau.png
    - assets/page-1/images/iconly-bold-star-kuP.png
    - assets/page-1/images/cart-ZkM.png
    - assets/page-1/images/iconsax-linear-location.png
    - assets/page-1/images/reebok.png
    - assets/page-1/images/cart-Cid.png
    - assets/page-1/images/iconly-bold-star-FaR.png
    - assets/page-1/images/iconly-bold-star-T1b.png
    - assets/page-1/images/brands-53o.png
    - assets/page-1/images/adidas.png
    - assets/page-1/images/mask-group-9rH.png
    - assets/page-1/images/image-6.png
    - assets/page-1/images/iconly-bold-star-uwo.png
    - assets/page-1/images/iconsax-linear-call.png
    - assets/page-1/images/iconsax-bold-google.png
    - assets/page-1/images/user-HcM.png
    - assets/page-1/images/mask-group-Sem.png
    - assets/page-1/images/iconly-bold-star-6jj.png
    - assets/page-1/images/back.png
    - assets/page-1/images/iconly-bold-star-pBB.png
    - assets/page-1/images/menu-1dT.png
    - assets/page-1/images/iconsax-linear-arrowleft.png
    - assets/page-1/images/iconsax-linear-eyeslash-2kH.png
    - assets/page-1/images/cellular-6KT.png
    - assets/page-1/images/iconsax-linear-edit2.png
    - assets/page-1/images/iconsax-linear-more-18d.png
    - assets/page-1/images/iconsax-linear-user-FdT.png
    - assets/page-1/images/brands-Szm.png
    - assets/page-1/images/image-5.png
    - assets/page-1/images/iconly-bold-star-RyK.png
    - assets/page-1/images/iconly-bold-star-fnq.png
    - assets/page-1/images/image-5-BRj.png
    - assets/page-1/images/iconsax-linear-card-7UV.png
    - assets/page-1/images/brands-mXP.png
    - assets/page-1/images/iconly-bold-star-m8D.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
